[package]
name = "migo-screen-capture"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", features = ["napi9"] }
napi-derive = "3"
scap = "0.0.8"

[build-dependencies]
napi-build = "2"

[profile.release]
lto = true
strip = true
